// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwJZGIX73XdB_XY082RsFOpp8wT1_rbe8',
    appId: '1:728922275032:web:dbf99eb08f2cc47717abad',
    messagingSenderId: '728922275032',
    projectId: 'db-catalanets',
    authDomain: 'db-catalanets.firebaseapp.com',
    storageBucket: 'db-catalanets.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9MKlj0DY35ogFYNxm7KaQCmhRdYKs-fM',
    appId: '1:728922275032:android:e8588b15a0e65c0417abad',
    messagingSenderId: '728922275032',
    projectId: 'db-catalanets',
    storageBucket: 'db-catalanets.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWfL6PRIdZlESyir5BpH5xqJ3kGbbNtqo',
    appId: '1:728922275032:ios:6fdfbc20712b1c5317abad',
    messagingSenderId: '728922275032',
    projectId: 'db-catalanets',
    storageBucket: 'db-catalanets.firebasestorage.app',
    iosBundleId: 'db.catalanets.catalanets',
  );
}
