platform :ios, '15.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Aquest bloc permet que Flutter gestioni els seus plugins automàticament
  # sense necessitar fitxers externs de configuració en aquest punt.
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target) if defined?(flutter_additional_ios_build_settings)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
