platform :ios, '15.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Forcem que tot es compili per a iOS 15.0
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      # Això ajuda a trobar mòduls que semblen "perduts"
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'PERMISSION_AUTHTRACKING=1']
    end
  end
end
