# Importació necessària per a les funcions de Flutter
require_relative '../.flutter-plugins-dependencies'

def flutter_install_all_ios_pods(ios_application_path = nil)
  native_additions_path = File.join(ios_application_path, '..', '.flutter-plugins-dependencies')
  if File.exist?(native_additions_path)
    sed_command = "sed -n 's/.*\"ios\":\[\(.*\)\].*/\1/p' #{native_additions_path} | tr ',' '\n' | xargs"
    pods = `#{sed_command}`.split
    pods.each do |pod|
      pod_name = pod.gsub('"', '').strip
      pod pod_name, :path => File.join(ios_application_path, '..', '.symlinks', 'plugins', pod_name, 'ios')
    end
  end
end

platform :ios, '15.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
